In [2]:
import pandas as pd
from pathlib import Path

BASE_DIR = Path.cwd()
if BASE_DIR.name == "NOTEBOOKS":
    BASE_DIR = BASE_DIR.parent

RAW_FILE = BASE_DIR / "DATA" / "RAW" / "NYC_311_RAW.csv"
PROCESSED_FILE = BASE_DIR / "DATA" / "PROCESSED" / "COMPLAINTS_CLEAN.csv"

print("BASE_DIR:", BASE_DIR)
print("RAW_FILE exists:", RAW_FILE.exists())
print("PROCESSED_FILE exists:", PROCESSED_FILE.exists())

BASE_DIR: c:\Users\Lakshay\OneDrive\Desktop\CIVICLENS_AI
RAW_FILE exists: True
PROCESSED_FILE exists: True

In [3]:
BASE_DIR = Path.cwd().parent
RAW_FILE = BASE_DIR / "DATA" / "RAW" / "NYC_311_RAW.csv"
PROCESSED_FILE = BASE_DIR / "DATA" / "PROCESSED" / "COMPLAINTS_CLEAN.csv"

In [4]:
raw_df = pd.read_csv(RAW_FILE, nrows=5000, low_memory=False)
raw_df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location,Zip Codes,Community Districts,Borough Boundaries,City Council Districts,Police Precincts
0,45050101,2019-12-01T02:04:01.000,NaN,DOT,Department of Transportation,Street Condition,Pothole,NaN,10001.0,WEST 29 STREET,...,NaN,NaN,40.745668,-73.987719,"{'longitude': '-73.9877188309367', 'latitude':...",NaN,NaN,NaN,NaN,NaN
1,45054936,2019-12-01T01:59:41.000,NaN,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,11223.0,178 AVENUE U,...,NaN,NaN,40.596475,-73.977721,"{'longitude': '-73.97772147626671', 'latitude'...",NaN,NaN,NaN,NaN,NaN
2,45049329,2019-12-01T01:59:08.000,NaN,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11207.0,807 SCHENCK AVENUE,...,NaN,NaN,40.660605,-73.883508,"{'longitude': '-73.8835082736363', 'latitude':...",NaN,NaN,NaN,NaN,NaN
3,45052046,2019-12-01T01:58:23.000,NaN,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11358.0,42-41 159 STREET,...,NaN,NaN,40.759994,-73.806856,"{'longitude': '-73.80685560533585', 'latitude'...",NaN,NaN,NaN,NaN,NaN
4,45054999,2019-12-01T01:58:07.000,NaN,NYPD,New York City Police Department,Illegal Parking,Commercial Overnight Parking,Street/Sidewalk,11426.0,88-49 237 STREET,...,NaN,NaN,40.729499,-73.729998,"{'longitude': '-73.72999847973517', 'latitude'...",NaN,NaN,NaN,NaN,NaN

In [5]:
raw_df.columns.tolist()

['Unique Key',
 'Created Date',
 'Closed Date',
 'Agency',
 'Agency Name',
 'Complaint Type',
 'Descriptor',
 'Location Type',
 'Incident Zip',
 'Incident Address',
 'Street Name',
 'Cross Street 1',
 'Cross Street 2',
 'Intersection Street 1',
 'Intersection Street 2',
 'Address Type',
 'City',
 'Landmark',
 'Facility Type',
 'Status',
 'Due Date',
 'Resolution Description',
 'Resolution Action Updated Date',
 'Community Board',
 'BBL',
 'Borough',
 'X Coordinate (State Plane)',
 'Y Coordinate (State Plane)',
 'Open Data Channel Type',
 'Park Facility Name',
 'Park Borough',
 'Vehicle Type',
 'Taxi Company Borough',
 'Taxi Pick Up Location',
 'Bridge Highway Name',
 'Bridge Highway Direction',
 'Road Ramp',
 'Bridge Highway Segment',
 'Latitude',
 'Longitude',
 'Location',
 'Zip Codes',
 'Community Districts',
 'Borough Boundaries',
 'City Council Districts',
 'Police Precincts']

In [6]:
raw_df["Complaint Type"].value_counts().head(20)

Complaint Type
HEAT/HOT WATER                       1042
Noise - Residential                  1017
Illegal Parking                       442
Blocked Driveway                      402
Noise - Commercial                    178
Sewer                                 173
Noise - Street/Sidewalk               123
Noise                                  90
Abandoned Vehicle                      87
Missed Collection (All Materials)      84
Broken Parking Meter                   73
Noise - Vehicle                        71
UNSANITARY CONDITION                   65
Water System                           61
General Construction/Plumbing          58
Noise - Helicopter                     54
Street Condition                       49
Lost Property                          43
Rodent                                 42
PLUMBING                               38
Name: count, dtype: int64

In [7]:
processed_df = pd.read_csv(PROCESSED_FILE)
processed_df.head()

,complaint_text,category,urgency,department,location
0,Street Condition Pothole,OTHER,LOW,GENERAL_ADMINISTRATION,NYC
1,Noise - Commercial Loud Music/Party,SAFETY,LOW,CAMPUS_SAFETY,NYC
2,Noise - Residential Loud Music/Party,SAFETY,LOW,CAMPUS_SAFETY,NYC
3,Noise - Residential Loud Music/Party,SAFETY,LOW,CAMPUS_SAFETY,NYC
4,Illegal Parking Commercial Overnight Parking,SAFETY,LOW,CAMPUS_SAFETY,NYC

In [8]:
processed_df["category"].value_counts()

category
OTHER             82436
SAFETY            57146
WATER             46434
ELECTRICITY        6877
INFRASTRUCTURE     4947
SANITATION         2160
Name: count, dtype: int64

In [9]:
processed_df["urgency"].value_counts()

urgency
LOW         192951
HIGH          6839
CRITICAL       110
MEDIUM         100
Name: count, dtype: int64

In [10]:
processed_df["department"].value_counts()

department
GENERAL_ADMINISTRATION        82436
CAMPUS_SAFETY                 57146
WATER_SERVICES                46434
ELECTRICAL_MAINTENANCE         6877
INFRASTRUCTURE_MAINTENANCE     4947
SANITATION_TEAM                2160
Name: count, dtype: int64